### ISSUE TITLE
Doc: Homepilot Rollotron pure Smart works

### ISSUE THREAD

**Issue by nicknol** [peribeir/homeassistant-rademacher#104]
Just to confirm that the Homepilot Rollotron pure Smart works perfectly with this integration. It's perhaps worth to mention in the documentation 

Thanks again for the integration - top job :)

**Comment by ccMatrix** [comment]
Can confirm! I installed a home pilot gateway with 2 rollotron pure smart today. Works well with home assistant now. Thanks for the integration.

**Comment by r-estermann** [comment]
Hi, also have Homepilot Rollotron pure smart here, connected with Homepilot Premium gateway.
wenn I try to close or open cover with Homeassistant, the devices will be unavailbale and i have to unpug/replug the power.
If I can help with logfiles oder something, let me know. thanks

**Comment by nicknol** [comment]
> Just to confirm that the Homepilot Rollotron pure Smart works perfectly with this integration. It's perhaps worth to mention in the documentation
> 
> Thanks again for the integration - top job :)

One more for the docs:
Smart flush-mounted roller shutter receiver (Rollladenaktor smart Unterputz) works with Homepilot premium gateway and this integration.

Thanks again!!
