### ISSUE TITLE
HA 2023.12

### ISSUE THREAD

**Issue by kabums** [peribeir/homeassistant-rademacher#105]
after upgrade Home Assistant to 2023.12 the integration won´t start.
ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package pyrademacher==0.9.2: ERROR: Cannot install pyrademacher==0.9.2 because these package versions have conflicting dependencies.

homeassistant.requirements.RequirementsNotFound: Requirements for rademacher not found: ['pyrademacher==0.9.2'].

**Comment by rubatec** [comment]
same issue

**Comment by kabums** [comment]
Still the same problem.
2023-12-07 20:22:42.373 ERROR (SyncWorker_8) [homeassistant.util.package] Unable to install package pyrademacher==0.9.2: ERROR: Cannot install pyrademacher==0.9.2 because these package versions have conflicting dependencies.
Requirements for rademacher not found: ['pyrademacher==0.9.2'].
homeassistant.requirements.RequirementsNotFound: Requirements for rademacher not found: ['pyrademacher==0.9.2'].

I am using HA Docker, HACS and the 2.1.1 Integration

**Comment by deltaphi** [comment]
I also had this problem, but I was on v1.13.1. After updating the integration to v2.1.1 and restarting Home Assistant, the integration loaded right away and everything is back in working order.

**Comment by peribeir** [comment]
Hi @kabums 

Did you restart Home Assistant after upgrading the integration?
From your logs, dependency from pyrademacher==0.9.2 shows that HA is still using version 1.11.1 of the integration.
Version 2.1.1 depends on pyrademacher 0.13.2 which should work with HA 2023.12

Please confirm that upgrade to 2.1.1 was done with success and HA was restarted afterwards.

**Comment by kabums** [comment]
Hello,
after i manually deleted the folder custom_components/rademacher, i was able to reinstall the integration.
Now everything is running as expected.
Many Thanks for the quick response and for your work on the Rademacher integration!
