### ISSUE TITLE
Integration will not be found in HACS default repositories

### ISSUE THREAD

**Issue by ggliniak** [peribeir/homeassistant-rademacher#107]
Hi,
running the newest HA version and the newest HACS version, but you integration unfortunately will not be found in HACS default repo, see attached screenshots. When trying to add the repo manually in HACS, it says it is in the default store. :-)

<img width="547" alt="Bildschirmfoto 2024-01-05 um 15 31 47" src="https://github.com/peribeir/homeassistant-rademacher/assets/120752228/46ebd257-37f3-4e96-9901-b8b74d5c74aa">
<img width="540" alt="Bildschirmfoto 2024-01-05 um 15 31 24" src="https://github.com/peribeir/homeassistant-rademacher/assets/120752228/3006998f-a019-46e8-aa1c-d2dd56e9c749">
<img width="534" alt="Bildschirmfoto 2024-01-05 um 15 30 51" src="https://github.com/peribeir/homeassistant-rademacher/assets/120752228/b250953e-827f-4d06-88bf-5f6a0e106bcf">

Best regards, G.

**Comment by peribeir** [comment]
Hi @ggliniak 
I cannot reproduce the issue you are having.
Here is a screenshot of HACS when I search for Rademacher:
![image](https://github.com/user-attachments/assets/b3416665-4823-48be-8639-7c5062e40a5b)

**Comment by peribeir** [comment]
Closing due to no response
