### ISSUE TITLE
Support for Homepilot Gateway premium

### ISSUE THREAD

**Issue by heindlalexander** [peribeir/homeassistant-rademacher#113]
Hi,

I think about buying 7 RolloTron radio swivel beltwinder (2550), so I also need to buy a gateway.

I read, that there are some issues with the Homepilot Gateway premium.
For what I understood, it is only supported without password? What does that mean in particular?

Or should I decide to buy the Rademacher Gateway instead?
There are also older version of it. Is this also 100% supported? (Smart2Smart, Gateway 2)
Or are there some disadvantages?

**Comment by ccMatrix** [comment]
I have the HomePilot gateway premium running with 2 rollotron pure smart. Works perfectly fine with Home Assistant using this integration. When you setup the gateway for the first time using the HomePilot app it may ask you if you want to set a password for it. Just tell it not to add one. Integration then just needed the IP or hostname of the gateway and found the devices.

**Comment by heindlalexander** [comment]
Thank you!
One more questions (if somebody knows): Is it possible to remove the password, if it is already set?
Moreover, is it planned to support the password in future too?

**Comment by ccMatrix** [comment]
You can remove/disable the local password via the HomePilot app. I've tested it on Android and it works.

**Comment by ccMatrix** [comment]
Since I set a password for testing the integration even detected it and asked for the password. So the integration seems to work with a local password for the gateway as well.

**Comment by heindlalexander** [comment]
thank you!

**Comment by r-estermann** [comment]
> I have the HomePilot gateway premium running with 2 rollotron pure smart. Works perfectly fine with Home Assistant using this integration. When you setup the gateway for the first time using the HomePilot app it may ask you if you want to set a password for it. Just tell it not to add one. Integration then just needed the IP or hostname of the gateway and found the devices.

I have trouble when I use homeassistant to move the rollotron pure smart. they just hang and i have to replug the power to gt them working again. With Homepilot app itself no trouble. any Ideas here?  anybody else some trouble ? thanks

**Comment by Lentzus-Ger** [comment]
Hi guys.
I´m not able to connect my Gateway Premium into Homeasisstant. 
Everytime when I type in the IP Adress, or the Host address the Home Assistant isn´t able to connect.
I have no password set or something else. 
Is it really possible to connect the Premium Gateway?

**Comment by Patuno** [comment]
Hey guys, sorry for reviving but I bought one of the Rademacher gateways (homepilot gateway premium) open box from amazon during a trip to Europe and when I came home (I'm from Argentina) and connected it realized the previous owner took the SD card with the firmware... I've been looking everywhere for a backup to copy it to a new SD card and hopefully get it running. Could one of you please help me out? Thanks a lot!
