### ISSUE TITLE
Rollotron runs into erros with position-data

### ISSUE THREAD

**Issue by wobeco** [peribeir/homeassistant-rademacher#120]
an automation running correctly until JUN24 shows errors from V.2024.7.x: Error: required key not provided @ data['position'].
Are there any suggestions to fix this?
Thank you.

**Comment by peribeir** [comment]
Hi,
are you still having this issue with latest version of Home Assistant and Integration?
If yes can you tell me which versions of both HA and Integration you are using?

**Comment by peribeir** [comment]
Closing due to no response
