### ISSUE TITLE
Moving the Rollotron pure smart to positions non 0 or 100 does not work

### ISSUE THREAD

**Issue by boom235** [peribeir/homeassistant-rademacher#121]
I have one HomePilot Gateway Premium and 5 Rollotron pure smart in Action. Everything works fine with the HomePilot app and also this HACS integration worked just fine.

First of all a big THX to you guys! This looks like a great integration to Home Assistant! Great Job!

unfortunately I discover major issues using position data (non 0 nor 100) using your latest stable version and the latest stable Home Assistant. At First I thought it is just inverted (60% equals 40%) but the longer I played with it and tried to make some simple Home Assistant scenarios work (like sun shade at 40% at a certain time), the more I got confused. It is executing some complete different commands then I send from Home Assistant. Almost random. Can there be any conflict with the gateway premium?

I would appreciate any hint on what I could try

**Comment by boom235** [comment]
Update: Today I found out that it is just the configuration of Home Assistant Scenarios for HomePilot devices that is a little buggy. If one manages to configure them once very patiently, the scenarios and automations work :-)

Still the positions are inverted. Setting the position to 60% in HomeAssistant leads to 40% in HomePilot. Which is fine for me, it is a bug, but if one knows it one can just configure it this way :-)

**Comment by peribeir** [comment]
Hi, thanks for the comments.
Good to know everything is working fine after all 😀
Regarding inverted percentage, that is related to the way Home Assistant interprets the value.
In HA 100% means fully open while 0% means fully closed. It is normal that the percentages are inverted compared to Homepilot app. That's the way HA works, no way around it 😉.
