### ISSUE TITLE
Regression with Version 2.1.3 / Duofern room thermostat controls no longer available

### ISSUE THREAD

**Issue by bash-public-willpower** [peribeir/homeassistant-rademacher#129]
**Summary:**  
In version 2.1.3, the Duofern room thermostat controls are no longer available. Previously, these controls were displayed correctly in earlier versions.

**Steps to Reproduce:**  
1. Update to version 2.1.3 of the application.
2. Check the controls for the Duofern room thermostat.

**Expected Behavior:**  
The controls for the Duofern room thermostat should be displayed as they were in previous versions.

**Actual Behavior:**  
The following message is displayed:  
> "This entity is no longer provided by the Rademacher integration. If this entity is no longer in use, delete it in the settings."

**Reproducibility:**  
Always

**Version:**  
2.1.3

**Additional Information:**  
This issue did not occur in versions prior to 2.1.3.
<img width="562" alt="Bildschirmfoto 2024-09-24 um 19 19 57" src="https://github.com/user-attachments/assets/61f1aef6-9f5a-4b2c-97da-75770cc4b498">

**Comment by oilid** [comment]
Same here… please fix this bug asap, thanks!

**Comment by technokatzen** [comment]
The logs for the weather station (the binary sensor for rain detection is also broken) and the thermostats all have the following error:
`...
File "/config/custom_components/rademacher/climate.py", line 118, in hvac_mode
  if device.has_relais_status and device.relais_value == 1

AttributeError: 'HomePilotThermostat' object has no attribute 'relais_value'. Did you mean: 'relais_status'`

**Comment by peribeir** [comment]
Hi, I inadvertely committed unfiished changes in 2.1.3. I'll release 2.1.4 with reverted changes.
Sorry for that.

**Comment by oilid** [comment]
Thank you @peribeir

**Comment by bash-public-willpower** [comment]
thank you very much, can confirm it works again
