### ISSUE TITLE
ZigBee lights not shown in Home Assistant

### ISSUE THREAD

**Issue by StefanKopetzky** [peribeir/homeassistant-rademacher#134]
Hi, first of all I am really new to Home Assistant and Homepilot, so maybe I am just doing something wrong.
But I tried to add my homepilot gateway to home assistant using this bridge and I cannot see the zigbee light devices.
In the homepilot app I've configured them and also can use them normally.
Other devices like the thermostats are shown also in home assistant and can be modified there.

Something I need to do specially for them? Any setting I am missing?
I use the current release v2.2.0, which should support the zigbee devices, right?

Thanks in advance
Steve

**Comment by peribeir** [comment]
I was not aware those were also zigbee lights. They will be added in version 2.2.1
