### ISSUE TITLE
Adding more devices?

### ISSUE THREAD

**Issue by dexxger** [peribeir/homeassistant-rademacher#136]
Hello,

I am using the following rademacher devices:

- DuoFern Universaldimmer 9476-1
- DuoFern Rohrmotor-Aktor 9471-1 (one in reverse for awning)
- DuoFern Mehrfachwandtaster 230V 9494-2 (switches to control rademacher devices and trigger automations in HA)
- DuoFern Wandtaster 1-Kanal 9494-3 
- SmartHome Box

I have added all my controls and sensors via rest so far by myself.

If you like I could provide you with the codes and information to add them to your integration.

**Comment by wach22** [comment]
Hi dexxger,
How did you reverse your 9471-1? Would implications does this have?
Would this be a solution for the problem of inverted position between HA and Rademacher (see #137)
Thanks.

**Comment by dexxger** [comment]
#awning
- platform: rest
  name: "awning"
  resource: "http://192.168.1.11/devices/12"
  value_template: >-
    {% for item in value_json.payload.device.capabilities %}
      {%- if item.name == "CURR_POS_CFG" -%}
        {{ float(item.value) }}
      {%- endif -%}
    {% endfor %}
  scan_interval: 1
  unique_id: 6f4df617-b687-4a5a-93a1-b5a244283c44

- platform: rest
  name: "Living Position"
  resource: "http://192.168.1.11/devices/13"
  value_template: >-
    {% for item in value_json.payload.device.capabilities %}
      {%- if item.name == "CURR_POS_CFG" -%}
        {{ 100 - float(item.value) }}
      {%- endif -%}
    {% endfor %}
  scan_interval: 1
  unique_id: a18f6b86-bf6b-4796-8d94-bd642102d3be

So the cover is "closed" when the awning is rolled up. 

The restcommands are also inverted. 
Example:
awning_winder_up:
  url: "http://192.168.1.11/devices/{{ did }}"
  method: PUT
  payload: '{"name":"POS_DOWN_CMD"}'
