### ISSUE TITLE
1.3.3 feedback regarding new device hub and configuration dialog

### ISSUE THREAD

**Issue by hklages** [peribeir/homeassistant-rademacher#14]
Hi Pedro. Just installed the new release 1.3.3

- The HomePilot is shown as device and the sensor "FW update" seems to work. THANKS!
- LED status can be changed - works fine.
- The device info is wrong - shows "Start2Smart" - its is not a big issue for me
- The configuration dialog shows an error message:
![rademacher](https://user-images.githubusercontent.com/17273119/150689713-ea56f137-c086-471d-96ef-1f02cfff65e4.jpg)
e

**Comment by peribeir** [comment]
Hi @hklages 
Thanks for the feedback!
As for the model, that was a typo in the code, I'll fix it in next release.
Regarding the error, I was not able to reproduce it. Can you check the Home Assistant logs to see more details on the error?
Thanks.

**Comment by peribeir** [comment]
Forget it, no need to check the logs. I saw the error now. I'll check.
Thanks again.
