### ISSUE TITLE
Homepilot 1: asking for password

### ISSUE THREAD

**Issue by argonid** [peribeir/homeassistant-rademacher#2]
Hi,

after having copied the folder in custom componentes and adding the "Rademacher" integration, it asks me for my local ip. That is no problem but after that I need to type in a password.
My homepilot does not have a password.

I am using Homepilot 1. Do you have an idea?

![image](https://user-images.githubusercontent.com/53093468/139593383-ae0a4b2f-a75c-4fa8-9197-e28f1fcf7ba7.png)

![image](https://user-images.githubusercontent.com/53093468/139593406-0a1cc066-3af5-4c97-b84d-17f78ab50430.png)

**Comment by peribeir** [comment]
Hi, I have just re-tested and it is working ok for me, but I don't actually have HomePilot, I have the smaller Start2smart.
Still, from what I read it should have same APIs.
I'm wondering if you have an older firmware. I've read that older firmware use a different API.
Can you check what is the firmware loaded into you HomePilot?
On my Hub, I can find it if I go to the web interface, then Settings -> Maintenance
![image](https://user-images.githubusercontent.com/7266291/141855837-8e8e2167-040c-4ba3-9988-90dcaa65cf59.png)

**Comment by flkontakt** [comment]
Hello, I have the same problem. Even my HomePilot 1 does not offer the possibility to enter a password. Is there a version of the integration that doesn't require a password?
![02](https://github.com/peribeir/homeassistant-rademacher/assets/77227687/cde53d25-54f0-4cf0-ab1a-8b5c28c07f2f)
![01](https://github.com/peribeir/homeassistant-rademacher/assets/77227687/69b3ea6e-82e2-4c49-81eb-b288c5e66188)

**Comment by BAERnado** [comment]
This device has a totally different interface and although most functionalities might be available it is not yet included in this addon.
I believe the whole WebUI is made up entirely different from the newer devices. This device is not capable of being handled by the Homepilot Android App, right? Otherwise we could sniff interactions.

**Comment by flkontakt** [comment]
> Dieses Gerät hat eine völlig andere Benutzeroberfläche und obwohl die meisten Funktionen verfügbar sind, ist es noch nicht in diesem Addon enthalten. Ich glaube, dass die gesamte WebUI völlig anders aufgebaut ist als die neueren Geräte. Dieses Gerät kann nicht von der Homepilot Android App bedient werden, oder? Andernfalls könnten wir Interaktionen erschnüffeln.

I don't use an app. I use iobroker with the appropriate adapter. There, only the ip address and the port are needed. But would like to use the functions in the home assistant
