### ISSUE TITLE
Cover Position

### ISSUE THREAD

**Issue by jproveta** [peribeir/homeassistant-rademacher#24]
Hi Pedro,

Acho que é Português, mas vou escrever em Inglês.

In the case of shutters (cover), is it not possible to invert the percentage? in the HomePilot system, for example, it appears 70% and in the HA it appears 30%.

Thanks,
JP

**Comment by MrWeidenMr** [comment]
Hi @all!

Perhaps it is possible to create a entity or attribute named "cover_position_reverse" with the reversed state. Then you could integrate it for example with the lovlace-slider-entity-row or you could show the revers state in lovelace.

**Comment by jproveta** [comment]
> Hi JP,
> 
> Sim, sou Português, é bom saber que há Portugueses a utilizar este componente :)
> 
> Now in English. The meaning of 0% and 100% in HA is inverted to the one from HomePilot. This is the way HA interprets the value, 0% is closed and 100% is open (while on HomePilot it is the other way around). For this reason I cannot change this behavior, because if I did, then opened and closed would be switched. Actually I needed to do the inversion in the component itself in order for HA to have expected behavior.
> 
> Cumprimentos, Pedro

Thanks, Obrigado pelo teu trabalho.

**Comment by hklages** [comment]
You can use the template platform to create new sensors  with (100% - position | int). 
To change the position you can use scripts and do the same there. 

I prefer the settings in this integration (in contradiction to HomePilot setting) as it teams well with lovelace cards "custom:slider-button-card"/"grid card": 


![Screenshot_20220211-092723_Home Assistant](https://user-images.githubusercontent.com/17273119/153559389-c56b05ac-d361-4249-b271-151aacdd94b4.jpg)
