### ISSUE TITLE
Set Temp

### ISSUE THREAD

**Issue by MrWeidenMr** [peribeir/homeassistant-rademacher#25]
Hi Pedro,

first of all thanks for your integration. It works very well!!

Is it possible to show and set the target-temperature at the "Temperature sensor DuoFern Room thermostat (DN:32501812_S)". I could only see the actual temperature and not the target.

**Comment by peribeir** [comment]
Hi @MrWeidenMr 

I don't have a thermostat to test myself, but I'll be glad to try and integrate it. I'll need your help to give me some inputs from HomePilot.

Are you familiar with the web interface of HomePilot?

**Comment by MrWeidenMr** [comment]
Hi!

I hope so. I'm new at home-assistant (for one week) but befor i found your integration i tried to integrate the devices by myself an they worked (except setting the temperature). Then I found your integration and I was very happy about that because thats more easyer for me.

 So I think i could help a bit. What do you need? The JSON from the sensor?

**Comment by peribeir** [comment]
Hi

Yes, can you start by sending the output of both the following:
http://[homepilot_ip]/v4/devices/[deviceid]
http://[homepilot_ip]/devices/[deviceid]

where [deviceid] is the did property of the sensor when you ask for all the sensors:
http://[homepilot_ip]/v4/devices?devtype=Sensor

**Comment by peribeir** [comment]
Thanks.
Hmm, this may be more difficult than I thought. But we'll get there. :)

Regarding the first URL, I think it was missing one part, can you send the response to:
http://[homepilot_ip]/v4/devices/1010013?devtype=Sensor

Another thing, in order to set the temperature , I need to figure out which command is sent to HP.
Do you know already what is the json sent in order to set the temperature?
If not, are you familiar with the browser DevTools (F12) in order to sniff the http request that is sent?

And one last question (for now) is set temp the only "action" you can make?

**Comment by MrWeidenMr** [comment]
Hi! 

Oh yes, when I use this url I get something:
`{"response":"get_meter","meter":{"description":"Wohnzimmer","deviceGroup":3,"did":1010013,"automations":[100],"readings":{"temperature_primary":21.5,"temperature_target":24.0},"timestamp":1644605682,"iconSetInverted":0,"iconSet":{"k":"iconset25"},"name":"Wohnzimmer-Raumthermostat","statusValid":true,"deviceNumber":"32501812_S","uid":"733e25_S_1","visible":true}}`

unfortunately I have no experience with DevTools. But the value that needs to be controlled should be "TARGET_TEMPERATURE_CFG". Or could you explain, what i have to do?

There are two actions i can do without going into the settings: set the temperature and switch between automatic and manual mode. In the settings are four temperature limits that can be set.

**Comment by MrWeidenMr** [comment]
Hi Pedro,

BIG thanks!!

It works!! I can set the temperature and homepilot/the sensor changes it, too!

![image](https://user-images.githubusercontent.com/99197872/153725580-596899a3-cb9d-47f2-a392-06acf6ed1bf1.png)

I can not switch between automatic mode and manual mode. But for me its not important, because i use it only in manual mode. =)

BR, MrWeidenMr

**Comment by MrWeidenMr** [comment]
Sure!

Manual setting:
`{"response":"get_device","device":{"description":"Wohnzimmer Raumthermostat","deviceGroup":5,"did":1010014,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset28"},"messages":[],"name":"Wohnzimmer-Raumthermostat","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":100,"Position":220,"acttemperatur":217,"relaisstatus":1,"automaticvalue":215,"manualoverride":0},"visible":true,"deviceNumber":"32501812_A","uid":"733e25_A_1","voiceControlledBy":"Google,Alexa","origin":"HomePilot","posMin":40,"posMax":400,"thresholds":[{"id":1,"value":215,"active":true},{"id":2,"value":220,"active":false},{"id":3,"value":215,"active":false},{"id":4,"value":170,"active":false}],"sceneConfig":["DIRECT_FUNCTION_CMD","CURR_TEMPERATURE_THRESH_CFG","AUTO_MODE_CFG"]}}`


automatic-mode:
`{"response":"get_device","device":{"description":"Wohnzimmer Raumthermostat","deviceGroup":5,"did":1010014,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset28"},"messages":[],"name":"Wohnzimmer-Raumthermostat","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":220,"acttemperatur":217,"relaisstatus":1,"automaticvalue":215,"manualoverride":100},"visible":true,"deviceNumber":"32501812_A","uid":"733e25_A_1","voiceControlledBy":"Google,Alexa","origin":"HomePilot","posMin":40,"posMax":400,"thresholds":[{"id":1,"value":215,"active":true},{"id":2,"value":220,"active":false},{"id":3,"value":215,"active":false},{"id":4,"value":170,"active":false}],"sceneConfig":["DIRECT_FUNCTION_CMD","CURR_TEMPERATURE_THRESH_CFG","AUTO_MODE_CFG"]}}`

The only difference I could spot ist "Manualbetrieb:0". "Manualbetrieb" means "manuel-mode". But this isnt a state, is it?

When I open the url without "v4" i get a different value at "TIME_AUTO_CFG".

manual-mode:
`{"error_description":"OK","error_code":0,"payload":{"device":{"capabilities":[{"name":"TEMPERATURE_INT_CFG","value":"21.8","min_value":"-40.0","max_value":"80.0","step_size":"0.1","read_only":false,"timestamp":1644774781},{"name":"POS_UP_CMD","read_only":false,"timestamp":-1},{"name":"INC_CMD","read_only":false,"timestamp":-1},{"name":"VERSION_CFG","value":"1.4-1","read_only":false,"timestamp":1644774781},{"name":"PROD_CODE_DEVICE_LOC","value":"32501812_A","read_only":false,"timestamp":-1},{"name":"REACHABILITY_EVT","value":"true","read_only":true,"timestamp":1644774781},{"name":"RESET_WO_PAIR_CMD","read_only":false,"timestamp":-1},{"name":"CONTACT_OPEN_CMD","read_only":false,"timestamp":-1},{"name":"NAME_DEVICE_LOC","value":"Wohnzimmer-Raumthermostat","read_only":false,"timestamp":-1},{"name":"PROT_ID_DEVICE_LOC","value":"733e25_A_1","read_only":false,"timestamp":-1},{"name":"CURR_TEMPERATURE_THRESH_CFG","value":"1","min_value":"1","max_value":"4","step_size":"1","read_only":false,"timestamp":1644774781},{"name":"INTF_ID_DEVICE_LOC","value":"3","read_only":false,"timestamp":-1},{"name":"ICONSET_LOC","value":"iconset28","read_only":false,"timestamp":-1},{"name":"DEVICE_TYPE_LOC","value":"5","read_only":false,"timestamp":-1},{"name":"RELAIS_STATE_CFG","value":"true","read_only":false,"timestamp":1644774781},{"name":"ICONSET_INV_LOC","value":"false","read_only":false,"timestamp":-1},{"name":"RMT_STOP_PAIR_CMD","read_only":false,"timestamp":-1},{"name":"VOICE_CONTROLLED_LOC","value":"Google,Alexa","read_only":false,"timestamp":-1},{"name":"REQ_STATUS_CMD","read_only":false,"timestamp":-1},{"name":"MAN_OVERW_ACTUATOR_CFG","value":"false","read_only":false,"timestamp":1644774781},{"name":"AUTO_MODE_CFG","value":"false","read_only":false,"timestamp":1644774781},{"name":"TARGET_TEMPERATURE_CFG","value":"22.0","min_value":"4.0","max_value":"40.0","step_size":"0.5","read_only":false,"timestamp":1644774781},{"name":"RESET_FULL_CMD","read_only":false,"timestamp":-1},{"name":"PUSH_CMD","read_only":false,"timestamp":-1},{"name":"PAIRING_CONFIRMED_LOC","value":"true","read_only":false,"timestamp":-1},{"name":"TEMPERATURE_THRESH_2_CFG","value":"22.0","min_value":"4.0","max_value":"40.0","step_size":"0.5","read_only":false,"timestamp":1644774781},{"name":"ID_DEVICE_LOC","value":"1010014","read_only":false,"timestamp":-1},{"name":"PROTOCOL_ID_CFG","value":"733e25","read_only":false,"timestamp":-1},{"name":"CONTACT_CLOSE_CMD","read_only":false,"timestamp":-1},{"name":"RMT_START_PAIR_CMD","read_only":false,"timestamp":-1},{"name":"TEMPERATURE_THRESH_3_CFG","value":"21.5","min_value":"4.0","max_value":"40.0","step_size":"0.5","read_only":false,"timestamp":1644774781},{"name":"TEMPERATURE_THRESH_1_CFG","value":"21.5","min_value":"4.0","max_value":"40.0","step_size":"0.5","read_only":false,"timestamp":1644774781},{"name":"STOP_CMD","value":"false","read_only":false,"timestamp":-1},{"name":"VIS_DEVICE_LOC","value":"true","read_only":false,"timestamp":-1},{"name":"RMT_START_UNPAIR_CMD","read_only":false,"timestamp":-1},{"name":"TEMPERATURE_THRESH_4_CFG","value":"17.0","min_value":"4.0","max_value":"40.0","step_size":"0.5","read_only":false,"timestamp":1644774781},{"name":"POS_DOWN_CMD","read_only":false,"timestamp":-1},{"name":"DESCR_DEVICE_LOC","value":"Wohnzimmer Raumthermostat","read_only":false,"timestamp":-1},{"name":"TIME_AUTO_CFG","value":"false","read_only":false,"timestamp":1644774781},{"name":"PING_CMD","read_only":false,"timestamp":-1},{"name":"DEC_CMD","read_only":false,"timestamp":-1}],"scenes":[]}}}`

auto-mode:
`{"error_description":"OK","error_code":0,"payload":{"device":{"capabilities":[{"name":"TEMPERATURE_INT_CFG","value":"21.7","min_value":"-40.0","max_value":"80.0","step_size":"0.1","read_only":false,"timestamp":1644774396},{"name":"POS_UP_CMD","read_only":false,"timestamp":-1},{"name":"INC_CMD","read_only":false,"timestamp":-1},{"name":"VERSION_CFG","value":"1.4-1","read_only":false,"timestamp":1644774396},{"name":"PROD_CODE_DEVICE_LOC","value":"32501812_A","read_only":false,"timestamp":-1},{"name":"REACHABILITY_EVT","value":"true","read_only":true,"timestamp":1644774396},{"name":"RESET_WO_PAIR_CMD","read_only":false,"timestamp":-1},{"name":"CONTACT_OPEN_CMD","read_only":false,"timestamp":-1},{"name":"NAME_DEVICE_LOC","value":"Wohnzimmer-Raumthermostat","read_only":false,"timestamp":-1},{"name":"PROT_ID_DEVICE_LOC","value":"733e25_A_1","read_only":false,"timestamp":-1},{"name":"CURR_TEMPERATURE_THRESH_CFG","value":"1","min_value":"1","max_value":"4","step_size":"1","read_only":false,"timestamp":1644774396},{"name":"INTF_ID_DEVICE_LOC","value":"3","read_only":false,"timestamp":-1},{"name":"ICONSET_LOC","value":"iconset28","read_only":false,"timestamp":-1},{"name":"DEVICE_TYPE_LOC","value":"5","read_only":false,"timestamp":-1},{"name":"RELAIS_STATE_CFG","value":"true","read_only":false,"timestamp":1644774396},{"name":"ICONSET_INV_LOC","value":"false","read_only":false,"timestamp":-1},{"name":"RMT_STOP_PAIR_CMD","read_only":false,"timestamp":-1},{"name":"VOICE_CONTROLLED_LOC","value":"Google,Alexa","read_only":false,"timestamp":-1},{"name":"REQ_STATUS_CMD","read_only":false,"timestamp":-1},{"name":"MAN_OVERW_ACTUATOR_CFG","value":"true","read_only":false,"timestamp":1644774396},{"name":"AUTO_MODE_CFG","value":"true","read_only":false,"timestamp":1644774396},{"name":"TARGET_TEMPERATURE_CFG","value":"22.0","min_value":"4.0","max_value":"40.0","step_size":"0.5","read_only":false,"timestamp":1644774396},{"name":"RESET_FULL_CMD","read_only":false,"timestamp":-1},{"name":"PUSH_CMD","read_only":false,"timestamp":-1},{"name":"PAIRING_CONFIRMED_LOC","value":"true","read_only":false,"timestamp":-1},{"name":"TEMPERATURE_THRESH_2_CFG","value":"22.0","min_value":"4.0","max_value":"40.0","step_size":"0.5","read_only":false,"timestamp":1644774396},{"name":"ID_DEVICE_LOC","value":"1010014","read_only":false,"timestamp":-1},{"name":"PROTOCOL_ID_CFG","value":"733e25","read_only":false,"timestamp":-1},{"name":"CONTACT_CLOSE_CMD","read_only":false,"timestamp":-1},{"name":"RMT_START_PAIR_CMD","read_only":false,"timestamp":-1},{"name":"TEMPERATURE_THRESH_3_CFG","value":"21.5","min_value":"4.0","max_value":"40.0","step_size":"0.5","read_only":false,"timestamp":1644774396},{"name":"TEMPERATURE_THRESH_1_CFG","value":"21.5","min_value":"4.0","max_value":"40.0","step_size":"0.5","read_only":false,"timestamp":1644774396},{"name":"STOP_CMD","value":"false","read_only":false,"timestamp":-1},{"name":"VIS_DEVICE_LOC","value":"true","read_only":false,"timestamp":-1},{"name":"RMT_START_UNPAIR_CMD","read_only":false,"timestamp":-1},{"name":"TEMPERATURE_THRESH_4_CFG","value":"17.0","min_value":"4.0","max_value":"40.0","step_size":"0.5","read_only":false,"timestamp":1644774396},{"name":"POS_DOWN_CMD","read_only":false,"timestamp":-1},{"name":"DESCR_DEVICE_LOC","value":"Wohnzimmer Raumthermostat","read_only":false,"timestamp":-1},{"name":"TIME_AUTO_CFG","value":"true","read_only":false,"timestamp":1644774396},{"name":"PING_CMD","read_only":false,"timestamp":-1},{"name":"DEC_CMD","read_only":false,"timestamp":-1}],"scenes":[]}}}`

**Comment by peribeir** [comment]
Well, "Manualbetrieb" can be used. Actually "manualoverride" is also different, but it seems to be inverted somehow.
Also, in the "without v4" version, AUTO_MODE_CFG is also different, and I think this is the attribute we need to set.
I'll try using Manualbetrieb, and add the action to change the mode using AUTO_MODE_CFG. And let's see if it works.

One other question: in auto mode, are you be able to set the target temperature?

**Comment by peribeir** [comment]
Meanwhile I've built beta.3, can you try it?
Unfortunately, HA doesn't have a "manual" mode, I've chosen "Heat/Cool" for the manual mode, auto is still "Auto".

**Comment by MrWeidenMr** [comment]
yes, it works! I can switch the status in HA und homepilot switches, too.

![image](https://user-images.githubusercontent.com/99197872/153772139-5ff08bc4-1f4a-4cbf-97d7-9272d10e69db.png)

"maunual mode" only means that the thermostat turns off when the target temperature is reached. if the temperature falls under the target temperature, it starts again.
"automatic mode" means that the target temperature is different at set times. e.g. 20 °C 8:00 - 22:00 and 18°C 22:00 - 8:00.

so "Heat/Cool" and "Auto" fits =)

Yes, in auto-mode i can set the actual target temperature with homepilot.

**Comment by peribeir** [comment]
Ok, cool!!

I assume Heizen/Kühlen means Heat/Cool, my german is not so good ;) ... Just kidding.

I'll consider this closed. I'll release it "officially" then.

**Comment by MrWeidenMr** [comment]
> Ok, cool!!
> 
> I assume Heizen/Kühlen means Heat/Cool, my german is not so good ;) ... Just kidding.
> 
> I'll consider this closed. I'll release it "officially" then.

Yes!! :) I'm so excited that you have an "ü" on your keyboard ;-P

Thanks a lot for work!!

BR

**Comment by peribeir** [comment]
Actually the umlaut has been removed from the Portuguese language more than 50 years ago, but we still keep it on our keyboards for some reason.
So if you ever think of moving to Portugal, you already know you can type German text on our keyboards, :-P

Enjoy the component.
Auf Wiedersehen ;)
