### ISSUE TITLE
Password will not work

### ISSUE THREAD

**Issue by Powerpitte** [peribeir/homeassistant-rademacher#29]
Hi,

I can't connect to HomePilot, neither to Version 5.3 nor 5.4. 

regards
Daniel

![image](https://user-images.githubusercontent.com/78154063/154468327-ff25c10e-cfad-4fb1-95a3-c62a63fda412.png)

**Comment by peribeir** [comment]
Hi @Powerpitte 

I'll need some logs from Home assistant.
Can you send HA logs right after you try to add the integration?

Br, Pedro.

**Comment by Powerpitte** [comment]
> Hi @Powerpitte
> 
> I'll need some logs from Home assistant. Can you send HA logs right after you try to add the integration?
> 
> Br, Pedro.

Hi @peribeir 
Thanks for coming back on this. Could you assist me for the best way to get the logs? What log level do I need?
BR Daniel

**Comment by peribeir** [comment]
Hi Daniel,

You can enable info logging for the component by adding the following to your configuration.yaml (located in the config folder):
```yaml
logger:
  default: warning
  logs:
    custom_components.rademacher: info
```
Then restart and retry adding the integration and reproduce the problem.

Then you can send me the logs in the homeassistant.log file (should be located in the same folder as the configuration.yaml).

In the end, you can remove the lines in configuration.yaml and restart again.

**Comment by Powerpitte** [comment]
Hi,

with Version 1.6.1 it works! Thanks!

BR Daniel
