### ISSUE TITLE
Awesome work!

### ISSUE THREAD

**Issue by deltaphi** [peribeir/homeassistant-rademacher#3]
Hi @peribeir,

in lack of another method to contact you I'm leaving an issue to give you feedback for your work on the Rademacher integration. I just installed it and it worked immediately with my Homepilot. Thank you very much!

@deltaphi

**Comment by peribeir** [comment]
Hi @deltaphi ,
Good to hear it worked. Thanks a lot.
I hope you find it useful.

**Comment by justaguy79** [comment]
Thinking about replacing a 20+ years old Rademacher with a new, connected model to integrate into HA. Thanks for your work and thanks for the comment, confirming it works! :)
