### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by 1192410** [peribeir/homeassistant-rademacher#32]
Hello,  

first I want to say thank you for developing that integration. I have a quite a few devices up and running and had connected it in the past through the API or Hoobs. Unfortunately I cannot connect to the integration with the following error messages: 

2022-02-22 20:36:24 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration tahoma: Exception importing custom_components.tahoma.config_flow
2022-02-22 20:36:24 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 230, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/rademacher/config_flow.py", line 183, in async_step_dhcp
    return await self.async_step_config()
  File "/config/custom_components/rademacher/config_flow.py", line 57, in async_step_config
    manager = await HomePilotManager.async_build_manager(api)
  File "/usr/local/lib/python3.9/site-packages/homepilot/manager.py", line 31, in async_build_manager
    manager.devices = {
  File "/usr/local/lib/python3.9/site-packages/homepilot/manager.py", line 32, in <dictcomp>
    id_type["did"]: await HomePilotManager.async_build_device(manager.api, id_type)
  File "/usr/local/lib/python3.9/site-packages/homepilot/manager.py", line 49, in async_build_device
    return await HomePilotThermostat.async_build_from_api(api, id_type["did"])
  File "/usr/local/lib/python3.9/site-packages/homepilot/thermostat.py", line 101, in async_build_from_api
    min_temperature=float(
TypeError: float() argument must be a string or a number, not 'NoneType'
2022-02-22 20:36:32 ERROR (MainThread) [pyhap.hap_handler] ('192.168.1.82', 64281): Client 18918035-6c91-4867-b0d0-f4fd6eca1fb2 attempted pair verify without being paired to HASS Bridge CI first.
2022-02-22 20:36:32 ERROR (MainThread) [pyhap.hap_handler] ('192.168.1.44', 57561): Client 18918035-6c91-4867-b0d0-f4fd6eca1fb2 attempted pair verify without being paired to HASS Bridge CI first.

<img width="294" alt="image" src="https://user-images.githubusercontent.com/73297737/155206875-3127a0c4-f322-4a45-acde-530a12394a65.png">
<img width="305" alt="image" src="https://user-images.githubusercontent.com/73297737/155207415-c189eb8e-6919-4852-9431-c4809c23fba5.png">

The IP address entered is 192.168.1.97 and is correct. Any help would be much appreciated. 

Thanks, Andreas

**Comment by peribeir** [comment]
Hi Andreas

Looks like it detected a thermostat but it is missing the min temperature setting.
Do you have a thermostat device? 
I just recently added the support for this type of device (and it was based on other people input) so it may be buggy.
Can you send me the output of capabilities API call:
http://[homepilot IP]/devices/[ID of thermostat]

Br,
Pedro

**Comment by 1192410** [comment]
Pedro, thanks for the quick reply. Yes, there is one thermostat, however it's not connected at the moment. 

{"error_description":"OK","error_code":0,"payload":{"device":{"capabilities":[{"name":"TEMPERATURE_INT_CFG","value":"20.78","read_only":false,"timestamp":1606589680},{"name":"EXT_OPEN_WINDOW_DETECT_EVT","value":"false","read_only":true,"timestamp":1606589680},{"name":"VERSION_CFG","value":"1.2-1","read_only":false,"timestamp":1606589680},{"name":"BATT_VALUE_EVT","value":"77","read_only":true,"timestamp":1606589680},{"name":"PROD_CODE_DEVICE_LOC","value":"35003064","read_only":false,"timestamp":-1},{"name":"REACHABILITY_EVT","value":"true","read_only":true,"timestamp":-1},{"name":"CONTACT_OPEN_CMD","read_only":false,"timestamp":1603442049},{"name":"NAME_DEVICE_LOC","value":"Heizkörper Esszimmer","read_only":false,"timestamp":-1},{"name":"PROT_ID_DEVICE_LOC","value":"e135ad_1","read_only":false,"timestamp":-1},{"name":"INTF_ID_DEVICE_LOC","value":"3","read_only":false,"timestamp":-1},{"name":"ICONSET_LOC","value":"iconset28","read_only":false,"timestamp":-1},{"name":"DEVICE_TYPE_LOC","value":"5","read_only":false,"timestamp":-1},{"name":"ICONSET_INV_LOC","value":"false","read_only":false,"timestamp":-1},{"name":"VOICE_CONTROLLED_LOC","value":"Alexa,Google","read_only":false,"timestamp":-1},{"name":"AUTO_MODE_CFG","value":"true","read_only":false,"timestamp":1606589680},{"name":"TARGET_TEMPERATURE_CFG","value":"18.0","min_value":"4.0","max_value":"28.0","step_size":"0.5","read_only":false,"timestamp":1614439432},{"name":"BATT_LOW_EVT","value":"false","read_only":true,"timestamp":1606589680},{"name":"PAIRING_CONFIRMED_LOC","value":"true","read_only":false,"timestamp":-1},{"name":"ID_DEVICE_LOC","value":"87","read_only":false,"timestamp":-1},{"name":"PROTOCOL_ID_CFG","value":"e135ad","read_only":false,"timestamp":-1},{"name":"CONTACT_CLOSE_CMD","read_only":false,"timestamp":1603442054},{"name":"BOOST_ACTIVE_CFG","value":"false","read_only":false,"timestamp":1606589680},{"name":"CONTACT_AUTO_CFG","value":"true","read_only":false,"timestamp":1601799560},{"name":"INT_OPEN_WINDOW_DETECT_EVT","value":"false","read_only":true,"timestamp":1606589680},{"name":"BATT_LOW_EVT_PUSH_TEXT","value":"","read_only":false,"timestamp":-1},{"name":"VIS_DEVICE_LOC","value":"true","read_only":false,"timestamp":-1},{"name":"BOOST_TIME_CFG","value":"15","min_value":"4","max_value":"60","step_size":"1","read_only":false,"timestamp":1606589680},{"name":"WAKE_UP_TIME_CFG","value":"15","min_value":"2","max_value":"60","step_size":"1","read_only":false,"timestamp":1606589680},{"name":"BATT_EMPTY_POS_CFG","value":"0","min_value":"0","max_value":"7","step_size":"1","read_only":false,"timestamp":1606017299},{"name":"BATT_LOW_EVT_PUSH_ENABLED","value":"false","read_only":false,"timestamp":-1},{"name":"DESCR_DEVICE_LOC","value":"Heizkörper Esszimmer","read_only":false,"timestamp":-1},{"name":"TIME_AUTO_CFG","value":"true","read_only":false,"timestamp":1606589680}],"scenes":[]}}}

**Comment by peribeir** [comment]
I just release v1.5.3. Can you check if it solves the problem?

BR,
Pedro

**Comment by 1192410** [comment]
Pedro, Thank  you. It's working. For me Rademacher has been the missing integration in HomeAssistant. Now it makes my life easier and I can get rid of all the workarounds.
