### ISSUE TITLE
Smoke detector - smoke attribute

### ISSUE THREAD

**Issue by 1192410** [peribeir/homeassistant-rademacher#34]
Hello,

another question from me. I was just checking the attributes of the smoke detector. The only attribute that is shown is the battery level, but not the smoke status. 

Current device details from the Rademacher integration

<img width="518" alt="image" src="https://user-images.githubusercontent.com/73297737/155343503-a8aa58f5-891e-4f73-bf27-176ec8963134.png">

same device via Homekit integration

<img width="544" alt="image" src="https://user-images.githubusercontent.com/73297737/155343842-52a23f07-4570-4f7b-a28e-68f5c6ba6c4d.png">

{"error_description":"OK","error_code":0,"payload":{"device":{"capabilities":[{"name":"VERSION_CFG","value":"","read_only":false,"timestamp":-1},{"name":"BATT_VALUE_EVT","value":"100","read_only":true,"timestamp":1645459781},{"name":"PROD_CODE_DEVICE_LOC","value":"32001664","read_only":false,"timestamp":-1},{"name":"REACHABILITY_EVT","value":"true","read_only":true,"timestamp":-1},{"name":"NAME_DEVICE_LOC","value":"Rauchwarnmelder Amelie","read_only":false,"timestamp":-1},{"name":"PROT_ID_DEVICE_LOC","value":"ab5027_1","read_only":false,"timestamp":-1},{"name":"INTF_ID_DEVICE_LOC","value":"3","read_only":false,"timestamp":-1},{"name":"ICONSET_LOC","value":"iconset26","read_only":false,"timestamp":-1},{"name":"DEVICE_TYPE_LOC","value":"3","read_only":false,"timestamp":-1},{"name":"ICONSET_INV_LOC","value":"false","read_only":false,"timestamp":-1},{"name":"BATT_LOW_EVT","value":"false","read_only":true,"timestamp":-1},{"name":"PAIRING_CONFIRMED_LOC","value":"true","read_only":false,"timestamp":-1},{"name":"BATTERY_LVL_PCT_MEA","value":"100","read_only":false,"timestamp":1645459781},{"name":"ID_DEVICE_LOC","value":"96","read_only":false,"timestamp":-1},{"name":"PROTOCOL_ID_CFG","value":"ab5027","read_only":false,"timestamp":-1},{"name":"SMOKE_STOP_EVT_PUSH_ENABLED","value":"false","read_only":false,"timestamp":-1},{"name":"SMOKE_DETECTION_MEA","value":"false","read_only":false,"timestamp":1601576037},{"name":"SMOKE_START_EVT_PUSH_ENABLED","value":"false","read_only":false,"timestamp":-1},{"name":"SMOKE_START_EVT","read_only":true,"timestamp":-1},{"name":"BATT_LOW_EVT_PUSH_TEXT","value":"","read_only":false,"timestamp":-1},{"name":"SMOKE_STOP_EVT_PUSH_TEXT","value":"","read_only":false,"timestamp":-1},{"name":"VIS_DEVICE_LOC","value":"true","read_only":false,"timestamp":-1},{"name":"SMOKE_START_EVT_PUSH_TEXT","value":"","read_only":false,"timestamp":-1},{"name":"SMOKE_STOP_EVT","read_only":true,"timestamp":1601576037},{"name":"BATT_LOW_EVT_PUSH_ENABLED","value":"false","read_only":false,"timestamp":-1},{"name":"DESCR_DEVICE_LOC","value":"Rauchwarnmelder Amelie","read_only":false,"timestamp":-1}],"scenes":[]}}}

Is there any chance to add the smoke status ? 

Thanks, Andreas

**Comment by 1192410** [comment]
Hi Pedro, 

thats the result: 

{"response":"get_meter","meter":{"description":"Rauchwarnmelder Amelie","deviceGroup":3,"did":96,"automations":[80],"readings":{"smoke_detected":false},"batteryStatus":100,"batteryLow":false,"timestamp":1645649531,"iconSetInverted":0,"iconSet":{"k":"iconset26"},"name":"Rauchwarnmelder Amelie","statusValid":true,"deviceNumber":"32001664","uid":"ab5027_1","visible":true}}

**Comment by peribeir** [comment]
Can you check if the smoke detector is now shown with v1.6.1?

BR,
Pedro.

**Comment by 1192410** [comment]
Yes, showing up. Thanks again and best regards, Andreas
