### ISSUE TITLE
Rademacher Multi-switch 9494-1

### ISSUE THREAD

**Issue by peribeir** [peribeir/homeassistant-rademacher#39]
I also have this multi-switch https://www.rademacher.de/shop/licht-heizung/fernbedienung/duofern-mehrfachwandtaster-bat-9494-1. So far with all the integrations I have up and running I never have seen this switch showing up except in homepilot itself. I'm just curious if there would be a way to integrate this device as well ?

PS: After some googleing I found this here https://community.home-assistant.io/t/rademacher-homepilot-in-home-assistant/204935/142 for the switch and I got it working.

_Originally posted by @1192410 in https://github.com/peribeir/homeassistant-rademacher/issues/36#issuecomment-1052220295_

**Comment by SpeedmaxX** [comment]
Hi, 

Do you have any plans for implementing this? 

Best regards, Markus

**Comment by der-berni** [comment]
See my PR #86

**Comment by peribeir** [comment]
PR has been merged.
Thanks @der-berni !!
