### ISSUE TITLE
Rollport SX5

### ISSUE THREAD

**Issue by MrWeidenMr** [peribeir/homeassistant-rademacher#40]
Hi Pedro!

I hope you're fine!

I've bought a Duofern Rollport sx5 for my garage. Perhaps you're interestet to integrate it. Let me know what you need.

Best regards
Marcel

**Comment by MrWeidenMr** [comment]
Hi Pedro,

here is the output of the webinterface:

`{"error_description":"OK","error_code":0,"payload":{"device":{"capabilities":[{"name":"LIGHT_BARR_TRG_EVT_PUSH_ENABLED","value":"false","read_only":false,"timestamp":-1},{"name":"CYCLES2000_ALARM_CFG","value":"false","read_only":false,"timestamp":1648800168},{"name":"INC_CMD","read_only":false,"timestamp":-1},{"name":"PROD_CODE_DEVICE_LOC","value":"45059071","read_only":false,"timestamp":-1},{"name":"GOTO_VENTIL_POS_CMD","read_only":false,"timestamp":-1},{"name":"REACHABILITY_EVT","value":"true","read_only":true,"timestamp":1648800168},{"name":"LIGHT_BARR_TRG_EVT","value":"false","read_only":true,"timestamp":1648800168},{"name":"NAME_DEVICE_LOC","value":"Garage","read_only":false,"timestamp":1647783819},{"name":"OPEN_SPEED_CFG","value":"2","min_value":"0","max_value":"2","step_size":"1","read_only":false,"timestamp":1648800168},{"name":"INTF_ID_DEVICE_LOC","value":"3","read_only":false,"timestamp":-1},{"name":"TURN_ON_CMD","read_only":false,"timestamp":-1},{"name":"MIN10_ALARM_CFG","value":"false","read_only":false,"timestamp":1648800168},{"name":"REQ_STATUS_CMD","read_only":false,"timestamp":-1},{"name":"AUTO_MODE_CFG","value":"false","read_only":false,"timestamp":1648800168},{"name":"PASS_DOOR_TRG_EVT_PUSH_ENABLED","value":"false","read_only":false,"timestamp":-1},{"name":"ID_DEVICE_LOC","value":"1010026","read_only":false,"timestamp":-1},{"name":"PROTOCOL_ID_CFG","value":"4e0f7d","read_only":false,"timestamp":-1},{"name":"BACK_JUMP_CFG","value":"false","read_only":false,"timestamp":1648800168},{"name":"LIGHT_BARR_TRG_EVT_PUSH_TEXT","value":"","read_only":false,"timestamp":-1},{"name":"GOTO_POS_CMD","min_value":"0","max_value":"100","step_size":"1","read_only":false,"timestamp":-1},{"name":"STOP_CMD","value":"false","read_only":false,"timestamp":-1},{"name":"VIS_DEVICE_LOC","value":"true","read_only":false,"timestamp":-1},{"name":"OBSTACLE_DET_EVT","value":"false","read_only":true,"timestamp":1648800168},{"name":"POS_DOWN_CMD","read_only":false,"timestamp":-1},{"name":"DESCR_DEVICE_LOC","value":"Garage","read_only":false,"timestamp":1647783820},{"name":"CURR_POS_CFG","value":"0","min_value":"0","max_value":"100","step_size":"1","read_only":false,"timestamp":1648800168},{"name":"POS_UP_CMD","read_only":false,"timestamp":-1},{"name":"VERSION_CFG","value":"2.1-1","read_only":false,"timestamp":1648800168},{"name":"TURN_OFF_CMD","read_only":false,"timestamp":-1},{"name":"RESET_WO_PAIR_CMD","read_only":false,"timestamp":-1},{"name":"PROT_ID_DEVICE_LOC","value":"4e0f7d_1","read_only":false,"timestamp":-1},{"name":"OBSTACLE_DET_EVT_PUSH_TEXT","value":"Hindernis erkannt","read_only":false,"timestamp":1647786181},{"name":"VENTIL_POS_MODE_CFG","value":"false","read_only":false,"timestamp":1648800168},{"name":"ICONSET_LOC","value":"iconset30","read_only":false,"timestamp":1647783790},{"name":"AUTOMATIC_CLOSING_CFG","value":"0","min_value":"0","max_value":"240","step_size":"30","read_only":false,"timestamp":1648800168},{"name":"DEVICE_TYPE_LOC","value":"8","read_only":false,"timestamp":-1},{"name":"PASS_DOOR_TRG_EVT","value":"false","read_only":true,"timestamp":1648800168},{"name":"ICONSET_INV_LOC","value":"false","read_only":false,"timestamp":-1},{"name":"RMT_STOP_PAIR_CMD","read_only":false,"timestamp":-1},{"name":"VOICE_CONTROLLED_LOC","value":"Google,Alexa","read_only":false,"timestamp":1647783866},{"name":"VENTIL_POS_CFG","value":"80","min_value":"0","max_value":"100","step_size":"1","read_only":false,"timestamp":1648800168},{"name":"RESET_FULL_CMD","read_only":false,"timestamp":-1},{"name":"PUSH_CMD","read_only":false,"timestamp":-1},{"name":"PAIRING_CONFIRMED_LOC","value":"true","read_only":false,"timestamp":-1},{"name":"RMT_START_PAIR_CMD","read_only":false,"timestamp":-1},{"name":"OBSTACLE_DET_EVT_PUSH_ENABLED","value":"true","read_only":false,"timestamp":1647786181},{"name":"PASS_DOOR_TRG_EVT_PUSH_TEXT","value":"","read_only":false,"timestamp":-1},{"name":"RMT_START_UNPAIR_CMD","read_only":false,"timestamp":-1},{"name":"TIME_AUTO_CFG","value":"false","read_only":false,"timestamp":1648800168},{"name":"PING_CMD","read_only":false,"timestamp":-1},{"name":"DEC_CMD","read_only":false,"timestamp":-1}],"scenes":[]}}}`

If you need more informations about the topics, please let me know.

BR
Marcel

**Comment by peribeir** [comment]
Hi @MrWeidenMr 

I believe this should be easy to integrate.
I'm assuming this device works as the Rollotron Shutters, so it should respond to the commands POS_UP_CMD, POS_DOWN_CMD, STOP_CMD, GOTO_POS_CMD. Can you confirm that?
Also, does this device show up when you call "http://ip/v4/devices". Can you send me the output of this call?
Thanks.

**Comment by MrWeidenMr** [comment]
Hi @peribeir,

yes, you're right.

Here is the output of "garage" in ip/v4/devides:
`{"response":"get_device","device":{"description":"Garage","deviceGroup":8,"did":1010026,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset30"},"messages":[],"name":"Garage","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":100,"Position":100},"visible":true,"deviceNumber":"45059071","uid":"4e0f7d_1","voiceControlledBy":"Google,Alexa","origin":"HomePilot","sceneConfig":["DIRECT_FUNCTION_CMD","GOTO_POS_CMD","POS_DOWN_CMD","AUTO_MODE_CFG"]}}`

BR

**Comment by peribeir** [comment]
Hi
I just added support for the Rolloport.
Can you check if v1.8.0 works for you?
Br,
Pedro.

**Comment by MrWeidenMr** [comment]
Hi @peribeir,

it works! Thanks :)
