### ISSUE TITLE
Rademacher blinds stop by % via HA automation?

### ISSUE THREAD

**Issue by justaguy79** [peribeir/homeassistant-rademacher#5]
It’s not an issue, but not sure where to post this elsewhere.

What options do I have via HA to control the blinds?

Can I stop Rademacher blinds by % via HA automation, like 90% closed? And is the blind status pushed back to HA?

Thanks a lot for your work, appreciate it very much!

**Comment by deltaphi** [comment]
You can set percentages from Home Assistant and the blinds will work as expected.

regarding the state, I think that the HA Integration polls the current state about once every 5 minutes. State updates are not immediate. I don’t know if this also applies when you set the state through HA. My HA does not show the percentages on the dashboard. However, I believe that the Up/Down arrows update correctly when moving the blinds through HA.

**Comment by peribeir** [comment]
You definitely can.
You just need to call the cover.set_cover_position service.
```
service: cover.set_cover_position
data:
  position: 45
target:
  entity_id: cover.living_room_blinds
```
As for the current state, it's being polled by HA, not sure what is the polling interval as it is using HA's default value. I believe it should be around 30 sec to 1 min. So you may see some discrepancy in the stat for a few seconds, when you open, close or set position.
