### ISSUE TITLE
Setup erneut versuchen: can't set attribute 'has_tilt'

### ISSUE THREAD

**Issue by Maaatze** [peribeir/homeassistant-rademacher#50]
The Connection to the Home Pilot is lost.
I have already done a new install. Now I have many mistakes. Version 1.9.0 and also 1.9.1.

**Comment by peribeir** [comment]
Please check v1.9.2, hope it fixes the issue.

**Comment by Maaatze** [comment]
Yes, it works.
Thank you! 


Am 16.07.2022 um 23:44 schrieb Pedro Ribeiro ***@***.***>:

﻿
Please check v1.9.2, hope it fixes the issue.
