### ISSUE TITLE
Device ping

### ISSUE THREAD

**Issue by thmnxo4** [peribeir/homeassistant-rademacher#54]
Hi,
if a device is not reachable in Homepilot, it is possible to ping - and then it reconnects.

I noticed that the ping feature is also available in the integration. But as soon as a device is not available the ping is not possible, too.

Is there a chance to make this running like in the Homepilot?

**Comment by peribeir** [comment]
Well I can try to leave the ping enabled even if device is not available.
Give me some days to make the change, then you can test if it works.

**Comment by peribeir** [comment]
Can you please test v1.9.7 and see if it works as expected?
