### ISSUE TITLE
Rademacher integration fails to start with HA Core 2022.11.5

### ISSUE THREAD

**Issue by eduardoribeiro** [peribeir/homeassistant-rademacher#55]
When HA starts it fails to launch Rademacher Integration and reports this error:

Unable to install package pyrademacher==0.6.6: ERROR: Cannot install pyrademacher==0.6.6 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip

**Comment by peribeir** [comment]
Please check if v1.9.4 works. I updated dependencies which seem to have been updated in HA
