### ISSUE TITLE
After update to latest version still get the error

### ISSUE THREAD

**Issue by eduardoribeiro** [peribeir/homeassistant-rademacher#57]
Logger: homeassistant.setup
Source: setup.py:202 
First occurred: 22:45:06 (1 occurrences) 
Last logged: 22:45:06

Setup failed for custom integration rademacher: Requirements for rademacher not found: ['pyrademacher==0.6.7'].

Logger: homeassistant.util.package
Source: util/package.py:98 
First occurred: 22:44:44 (3 occurrences) 
Last logged: 22:45:06

Unable to install package pyrademacher==0.6.7: ERROR: Cannot install pyrademacher==0.6.7 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip

**Comment by peribeir** [comment]
I'll try to reproduce the issue in my environment.
Strangely it's not erroring in my running HA instance.

**Comment by eduardoribeiro** [comment]
By the way, I'm using HA Core 2022.12.0b1

**Comment by peribeir** [comment]
I think I got it. Please test with v1.9.5.

**Comment by peribeir** [comment]
I actually need to do an update to be compatible with previous versions of HA.
Please test with v1.9.6 once I publish it.
