### ISSUE TITLE
FR: Rademacher RolloTron - get or set ventilating position (Lüftungsposition)

### ISSUE THREAD

**Issue by tispokes** [peribeir/homeassistant-rademacher#68]
Hi, would be nice to be able to get or even set the ventilating postion in home assistant. 

![image](https://user-images.githubusercontent.com/45465820/219370824-978f1b22-1a25-4e59-9a7b-f9589712e98e.png)

**Comment by peribeir** [comment]
Hi
I can definitely add support for ventilation position. I didn't add it previously because I don't personally use it.
I'll try to do it for next release.

**Comment by tispokes** [comment]
Would be awesome!

And another question, according to Rademacher, the standard and comfort models have a choice of motor speed. Unfortunately these motor speeds are only available for the automatic programs. But I bought it already and it was only visible in the manual. Annoying.
But the question is, have you ever seen this options somewhere?

From installing on the are more quiet as basis and really a softer start and stopping.
Just wanted to share this new knowledge 😅

**Comment by peribeir** [comment]
I own several Rollotron 1200 and I never saw those controls. Which models do you have?

**Comment by tispokes** [comment]
I started with the 1200 at Monday. Now i have also an 1400 and order a 1800.
1200 is the basis model, only one speed. The other ones (standard and comfort) has 3 motor speed, but unfortunately only in automatic mode, is quieter, has soft Start stop and finer control of the motor. Got one cheap, by coincidence. Otherwise i would not know.

![Screenshot_20230218-110649](https://user-images.githubusercontent.com/45465820/219977972-b4d0c891-bac1-408a-a699-c39d163d2d37.png)
From the 1400 manual, can also make a screenshot of the English version.

When you check the v4-api (don't know better how to describe e.g. http://bridge.local/v4/devices/1 ), have you ever wondered about `Schlafzimmer","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3}`

Maybe this is the speed setting.
Edit: tested it on the 1400, it is still set to 3

**Comment by peribeir** [comment]
I never understood what those properties represent, actually. But seems not to be related.
I'm just adding the ventilation controls right now, and I'll close this issue.
Let's move this (motor speed) into another conversation. Can you please open another issue for the motor speed? Meanwhile instead of the v4-api, please send the output of the other api (not sure how to call it, http://bridge.local/devices/1).

**Comment by peribeir** [comment]
Just released v1.11.1. Added:
  * New switch for controlling Ventilation Position Mode (on / off)
  * New slider number entity for controlling the current Ventilation Position (between 0/100%).
    * **NOTE**: The ventilation position is value matches the way Home Assistant represents cover position (0% means totally closed, 100% means totally open)

**Comment by tispokes** [comment]
Update installed, thanks for quick support 😍
Just one note. If I switch off the vent pos mode, vent pos shows "Not available". Maybe would be nice to get this information anyways. But details, works fine.

Checked the PRs on both repos, as every time when coding. When you know what to do, it's easy 🙃

**Comment by peribeir** [comment]
Actually I intentionally put it to unavailable in order to match the Bridge's UI.
I'm not sure if we try to set a new value when vent pos mode is off, will have any effect. Maybe I'll check it later.

As for the coding, I'm happy to do the changes, but maybe next time you can have a try and do it yourself 😉

**Comment by tispokes** [comment]
Have a broken right hand. Everything i do is on my mobile phone atm. So no programming at the moment. The install of the rollotron was with a friend's hand. Otherwise i would have 😉

But you know your code better.

Ah you are right, I can't set a new value but I can see the value. Doesn't matter. Was just my 2 cents and a feedback.
