### ISSUE TITLE
FR: add motor speed of possible (for non-Basis RolloTron only)

### ISSUE THREAD

**Issue by tispokes** [peribeir/homeassistant-rademacher#71]
Continue of #68 side discussion

REST HTTP GET from RolloTron 1400 via http://bridge.local/devices/1

`{"error_description":"OK","error_code":0,"payload":{"device":{"capabilities":[{"name":"INC_CMD","read_only":false,"timestamp":-1},{"name":"PROD_CODE_DEVICE_LOC","value":"14234511","read_only":false,"timestamp":-1},{"name":"GOTO_VENTIL_POS_CMD","read_only":false,"timestamp":-1},{"name":"REACHABILITY_EVT","value":"true","read_only":true,"timestamp":1676845019},{"name":"NAME_DEVICE_LOC","value":"RolloTron Schlafzimmer","read_only":false,"timestamp":1676787879},{"name":"INTF_ID_DEVICE_LOC","value":"3","read_only":false,"timestamp":-1},{"name":"GOTO_DAWN_POS_CMD","read_only":false,"timestamp":-1},{"name":"REQ_STATUS_CMD","read_only":false,"timestamp":-1},{"name":"ID_DEVICE_LOC","value":"1","read_only":false,"timestamp":-1},{"name":"PROTOCOL_ID_CFG","value":"406d1d","read_only":false,"timestamp":-1},{"name":"GOTO_POS_CMD","min_value":"0","max_value":"100","step_size":"1","read_only":false,"timestamp":-1},{"name":"SUN_STOP_CMD","read_only":false,"timestamp":-1},{"name":"STOP_CMD","value":"false","read_only":false,"timestamp":-1},{"name":"BLOCK_DET_EVT_PUSH_TEXT","value":"Blockierung erkannt","read_only":false,"timestamp":1676714155},{"name":"VIS_DEVICE_LOC","value":"true","read_only":false,"timestamp":-1},{"name":"OBSTACLE_DET_EVT","value":"false","read_only":true,"timestamp":1676845019},{"name":"BLOCK_DET_EVT_PUSH_ENABLED","value":"true","read_only":false,"timestamp":1676714155},{"name":"BLOCK_DET_EVT","value":"false","read_only":true,"timestamp":1676845019},{"name":"POS_DOWN_CMD","read_only":false,"timestamp":-1},{"name":"DESCR_DEVICE_LOC","value":"","read_only":false,"timestamp":1676787877},{"name":"CURR_POS_CFG","value":"78","min_value":"0","max_value":"100","step_size":"1","read_only":false,"timestamp":1676845019},{"name":"POS_UP_CMD","read_only":false,"timestamp":-1},{"name":"VERSION_CFG","value":"1.5-2","read_only":false,"timestamp":1676845019},{"name":"RESET_WO_PAIR_CMD","read_only":false,"timestamp":-1},{"name":"PROT_ID_DEVICE_LOC","value":"406d1d_1","read_only":false,"timestamp":-1},{"name":"OBSTACLE_DET_EVT_PUSH_TEXT","value":"Hindernis erkannt","read_only":false,"timestamp":1676714155},{"name":"VENTIL_POS_MODE_CFG","value":"true","read_only":false,"timestamp":1676845019},{"name":"ICONSET_LOC","value":"iconset8","read_only":false,"timestamp":1676714112},{"name":"DEVICE_TYPE_LOC","value":"2","read_only":false,"timestamp":-1},{"name":"ICONSET_INV_LOC","value":"false","read_only":false,"timestamp":-1},{"name":"RMT_STOP_PAIR_CMD","read_only":false,"timestamp":-1},{"name":"VOICE_CONTROLLED_LOC","value":"Alexa,Google","read_only":false,"timestamp":-1},{"name":"VENTIL_POS_CFG","value":"78","min_value":"0","max_value":"100","step_size":"1","read_only":false,"timestamp":1676845019},{"name":"RESET_FULL_CMD","read_only":false,"timestamp":-1},{"name":"PUSH_CMD","read_only":false,"timestamp":-1},{"name":"PAIRING_CONFIRMED_LOC","value":"true","read_only":false,"timestamp":-1},{"name":"RMT_START_PAIR_CMD","read_only":false,"timestamp":-1},{"name":"SUN_PROG_ACTIVE_EVT","value":"false","read_only":true,"timestamp":1676845019},{"name":"GOTO_DUSK_POS_CMD","read_only":false,"timestamp":-1},{"name":"SUN_START_CMD","read_only":false,"timestamp":-1},{"name":"OBSTACLE_DET_EVT_PUSH_ENABLED","value":"true","read_only":false,"timestamp":1676714155},{"name":"RMT_START_UNPAIR_CMD","read_only":false,"timestamp":-1},{"name":"PING_CMD","read_only":false,"timestamp":-1},{"name":"DEC_CMD","read_only":false,"timestamp":-1}],"scenes":[]}}}`

**Comment by peribeir** [comment]
Unfortunately I don't see any property that could represent the motor speed.
Can you try with different speeds to see if anything changes in this api?
And another question, can you actually change the speed using the HomePilot UI?

**Comment by tispokes** [comment]
Unfortunately it is not possible in home pilot. I contacted Rademacher already, because it's more than stupid to only open this feature for the automatic modes. Also it was not declared on the boxing of the RolloTron. Only that you can adjust the motor speed.

I checked the api (both) already, no change. Hope Rademacher will bring an fw update for real smart Home users 😅
Will comment when I got feedback, otherwise I close the FR

**Comment by peribeir** [comment]
Closing issue. Feature is not possible with current Homepilot API/FW Version.
