### ISSUE TITLE
Rademacher IP changed and Home Assistant show it like new instance

### ISSUE THREAD

**Issue by misa1515** [peribeir/homeassistant-rademacher#72]
Hello,
for yet configured Rademacher device (in Home Assistant with created and working Automatizations) was changed IP address and now HA found new Rademachet instance.
How can be, in HA, changed IP address of Rademacher to new one?
Thanks.

**Comment by peribeir** [comment]
Hello
Unfortunately I made a mistake when I first built the integration, I used the IP Address as the unique identifier for each instance.
I will update it to use the MAC Address which is fixed (and following HA recommendations).

Note1: if IP changes again, unfortunately it will not update automatically in HA until you restart HA.
Note2: Automatic IP change detection is only possible if bridge is configured to use DHCP for IP assignment, if static IP is used and it is changed, user will have to manually delete and re-add integration.
