### ISSUE TITLE
FR: Add temperature threshholds to control heating and cooling

### ISSUE THREAD

**Issue by CoolID2** [peribeir/homeassistant-rademacher#74]
Hi, 
could you please evaluate the 4 temperature thresholds ( TEMPERATURE_THRESH_1_CFG - TEMPERATURE_THRESH_4_CFG)? So that you could read them out and ideally also set them.

My heating and lowering temperatures are set individually in each room. I have set these in FHEM using these four threshold variables and have built my DO/IF's accordingly.

After I am just about to move from FHEM to Homeassistant, I am missing these values for the automations. To take auxiliary variables for it I would find somewhat cumbersome.
In addition, you could set the values on the device itself.

{"error_description":"OK","error_code":0,"payload":{"device":{"capabilities":[{"name":"TEMPERATURE_INT_CFG","value":"22.0","min_value":"-40.0","max_value":"80.0","step_size":"0.1","read_only":false,"timestamp":1682867652},{"name":"POS_UP_CMD","read_only":false,"timestamp":-1},{"name":"INC_CMD","read_only":false,"timestamp":-1},{"name":"VERSION_CFG","value":"1.3-1","read_only":false,"timestamp":1682867652},{"name":"PROD_CODE_DEVICE_LOC","value":"32501812_A","read_only":false,"timestamp":-1},{"name":"REACHABILITY_EVT","value":"true","read_only":true,"timestamp":1682867652},{"name":"RESET_WO_PAIR_CMD","read_only":false,"timestamp":-1},{"name":"CONTACT_OPEN_CMD","read_only":false,"timestamp":-1},{"name":"NAME_DEVICE_LOC","value":"AZ_Fussbodenheizung","read_only":false,"timestamp":-1},{"name":"PROT_ID_DEVICE_LOC","value":"7326b7_A_1","read_only":false,"timestamp":-1},{"name":"CURR_TEMPERATURE_THRESH_CFG","value":"1","min_value":"1","max_value":"4","step_size":"1","read_only":false,"timestamp":1682867652},{"name":"INTF_ID_DEVICE_LOC","value":"3","read_only":false,"timestamp":-1},{"name":"ICONSET_LOC","value":"iconset28","read_only":false,"timestamp":-1},{"name":"DEVICE_TYPE_LOC","value":"5","read_only":false,"timestamp":-1},{"name":"RELAIS_STATE_CFG","value":"false","read_only":false,"timestamp":1682867652},{"name":"ICONSET_INV_LOC","value":"false","read_only":false,"timestamp":-1},{"name":"RMT_STOP_PAIR_CMD","read_only":false,"timestamp":-1},{"name":"VOICE_CONTROLLED_LOC","value":"Alexa,Google","read_only":false,"timestamp":-1},{"name":"REQ_STATUS_CMD","read_only":false,"timestamp":-1},{"name":"MAN_OVERW_ACTUATOR_CFG","value":"false","read_only":false,"timestamp":1682867652},{"name":"TARGET_TEMPERATURE_CFG","value":"21.0","min_value":"4.0","max_value":"40.0","step_size":"0.5","read_only":false,"timestamp":1682867652},{"name":"RESET_FULL_CMD","read_only":false,"timestamp":-1},{"name":"PUSH_CMD","read_only":false,"timestamp":-1},{"name":"PAIRING_CONFIRMED_LOC","value":"true","read_only":false,"timestamp":-1},{"name":"TEMPERATURE_THRESH_2_CFG","value":"19.0","min_value":"4.0","max_value":"40.0","step_size":"0.5","read_only":false,"timestamp":1682867652},{"name":"ID_DEVICE_LOC","value":"4","read_only":false,"timestamp":-1},{"name":"PROTOCOL_ID_CFG","value":"7326b7","read_only":false,"timestamp":-1},{"name":"CONTACT_CLOSE_CMD","read_only":false,"timestamp":-1},{"name":"RMT_START_PAIR_CMD","read_only":false,"timestamp":-1},{"name":"TEMPERATURE_THRESH_3_CFG","value":"10.0","min_value":"4.0","max_value":"40.0","step_size":"0.5","read_only":false,"timestamp":1682867652},{"name":"TEMPERATURE_THRESH_1_CFG","value":"22.0","min_value":"4.0","max_value":"40.0","step_size":"0.5","read_only":false,"timestamp":1682867652},{"name":"STOP_CMD","value":"false","read_only":false,"timestamp":-1},{"name":"VIS_DEVICE_LOC","value":"true","read_only":false,"timestamp":-1},{"name":"RMT_START_UNPAIR_CMD","read_only":false,"timestamp":-1},{"name":"TEMPERATURE_THRESH_4_CFG","value":"10.0","min_value":"4.0","max_value":"40.0","step_size":"0.5","read_only":false,"timestamp":1682867652},{"name":"POS_DOWN_CMD","read_only":false,"timestamp":-1},{"name":"DESCR_DEVICE_LOC","value":"Ihre Gerätebeschreibung","read_only":false,"timestamp":-1},{"name":"PING_CMD","read_only":false,"timestamp":-1},{"name":"DEC_CMD","read_only":false,"timestamp":-1}],"scenes":[]}}}

**Comment by peribeir** [comment]
Hi,

If I understand well. The idea is to add 4 Number sliders, one for each threshold. And be able to set the threshold temperature by moving the slider. Is that correct?
Something like this:
![image](https://github.com/peribeir/homeassistant-rademacher/assets/7266291/f6ef3e12-836c-4dee-80ce-3ccd7c568ffb)

**Comment by peribeir** [comment]
Also I have one question, do you know the what is the HTTP request content when you change the threshold?
Is it like this?
`{"TEMPERATURE_THRESH_1_CFG":24.4}`
And is it an HTTP POST or HTTP PUT?
Thanks

**Comment by CoolID2** [comment]
Hi, 
that would be for me the luxury variant and a great suggestion from you. 

It is only important to me that I have each threshold as a separate entity, so that I can include them in my automations.
 Example: 
Heatup: Set Temperature to sensor.bath_threshold_1
Cooldown: Set Temperature to sensor.bath_threshold_2 
SwitchOff: Set Temperature to sensor. bath_threhold_4 (which belongs to 5°)

Some thermostats, for example on radiators (like Bosch BTH-RA or AVM 301), can be switched off in summer. 
With Rademacher, unfortunately, you have to do this via the temperature control to 5°C. 

I don't know wich HTTP request will be used. I haven't checked. 


Sorry for the trouble and thank you for your efforts 

Best Regards

**Comment by peribeir** [comment]
I'll be adding the entities as I mentioned in v1.13.1. Please check if it fits the requirements and give me some feedback.
If it doesn't work correctly or you think something can be improved, please reopen this issue.

**Comment by CoolID2** [comment]
Hi,
looks good. I think you have done a great job here. 
I was able to include the new entities in my automation in YAML mode super easy. 

Thanks a lot for that
