### ISSUE TITLE
belt winder speed setting

### ISSUE THREAD

**Issue by 1192410** [peribeir/homeassistant-rademacher#85]
Hi Pedro, 

as it seems you are currently developing and enhancing the integration I would have one question. Would it be possible to select the motor speed somehow in the integration as it is possilble in the menu of the belt winders ? 

Many thanks and best regards, Andreas

<img width="885" alt="image" src="https://github.com/peribeir/homeassistant-rademacher/assets/73297737/35c16636-4497-4ed3-971a-72fe86bbb175">

**Comment by peribeir** [comment]
Hi Andreas,

As far as I know, it is not possible to change the motor speed through HomePilot Gateway (refer to issue #71 where this was discussed).

Do you know if this is possible?

Best regards.

**Comment by 1192410** [comment]
Hi Pedro, 

I have not seen the discussion. I think it's not possible then, unfortunately. But I will also contact Rademacher directly and try to get this wish on their enhancement requests. 

Many thanks and best regards, Andreas
