### ISSUE TITLE
Error occurred loading configuration flow for integration rademacher

### ISSUE THREAD

**Issue by hciftci** [peribeir/homeassistant-rademacher#87]
Jul 20 23:22:17 homeassistant hass[1030]: 2023-07-20 23:22:17.016 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.rademacher.config_flow
Jul 20 23:22:17 homeassistant hass[1030]: Traceback (most recent call last):
Jul 20 23:22:17 homeassistant hass[1030]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 744, in get_platform
Jul 20 23:22:17 homeassistant hass[1030]:     cache[full_name] = self._import_platform(platform_name)
Jul 20 23:22:17 homeassistant hass[1030]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 761, in _import_platform
Jul 20 23:22:17 homeassistant hass[1030]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
Jul 20 23:22:17 homeassistant hass[1030]:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
Jul 20 23:22:17 homeassistant hass[1030]:     return _bootstrap._gcd_import(name[level:], package, level)
Jul 20 23:22:17 homeassistant hass[1030]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Jul 20 23:22:17 homeassistant hass[1030]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Jul 20 23:22:17 homeassistant hass[1030]:   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
Jul 20 23:22:17 homeassistant hass[1030]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Jul 20 23:22:17 homeassistant hass[1030]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Jul 20 23:22:17 homeassistant hass[1030]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Jul 20 23:22:17 homeassistant hass[1030]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Jul 20 23:22:17 homeassistant hass[1030]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Jul 20 23:22:17 homeassistant hass[1030]:   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
Jul 20 23:22:17 homeassistant hass[1030]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Jul 20 23:22:17 homeassistant hass[1030]:   File "/home/homeassistant/.homeassistant/custom_components/rademacher/__init__.py", line 24, in <module>
Jul 20 23:22:17 homeassistant hass[1030]:     from homepilot.manager import HomePilotManager
Jul 20 23:22:17 homeassistant hass[1030]:   File "/srv/homeassistant/lib/python3.9/site-packages/homepilot/manager.py", line 5, in <module>
Jul 20 23:22:17 homeassistant hass[1030]:     from .hub import HomePilotHub
Jul 20 23:22:17 homeassistant hass[1030]:   File "/srv/homeassistant/lib/python3.9/site-packages/homepilot/hub.py", line 14, in <module>
Jul 20 23:22:17 homeassistant hass[1030]:     class HomePilotHub(HomePilotDevice):
Jul 20 23:22:17 homeassistant hass[1030]:   File "/srv/homeassistant/lib/python3.9/site-packages/homepilot/hub.py", line 23, in HomePilotHub
Jul 20 23:22:17 homeassistant hass[1030]:     _download_progress: int | bool
Jul 20 23:22:17 homeassistant hass[1030]: TypeError: unsupported operand type(s) for |: 'type' and 'type'
Jul 20 23:22:17 homeassistant hass[1030]: 2023-07-20 23:22:17.023 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration rademacher: Exception importing custom_components.rademacher.config_flow

**Comment by peribeir** [comment]
Hi @hciftci 

Are you using the new Homepilot Gateway Premium?
If so, the error was due to new interface which was not supported by the integration.

I just release a new version (2.0) which should be compatible with the new gateways, can you try it?
Please note that if you do have the new gateway, and you have local password for it, the integration will not work yet, but you can try disabling password for now and see if it works.

**Comment by peribeir** [comment]
Closing due to no answer
