### ISSUE TITLE
Use Scenes from HomePilot in HomeAssistant

### ISSUE THREAD

**Issue by rhmunich** [peribeir/homeassistant-rademacher#88]
Hi there,
Is there a way to integrate "scenes" which are set up in the HomePilot into HomeAssistant?
It would be great to have the HomePilot-scenes available in HomeAssistant so that I do not have to replicate them as separate HomeAssistant automations.
Many thanks, Ralph

**Comment by peribeir** [comment]
Hi @Hochstatter 

Unfortunately, I own a Start2Smart gateway which is a stripped down version of the Homepilot GW. And it doesn't support Scenes.
Maybe you can help me adding entities for scenes in the integration.

Can I ask you to send me the result of some URLs in your browser?

**Comment by deltaphi** [comment]
I would also be interested in this feature (Workaround for #91?) and have a HomePilot. Can I help out with URL responses?

**Comment by rhmunich** [comment]
> Hi @Hochstatter
> 
> Unfortunately, I own a Start2Smart gateway which is a stripped down version of the Homepilot GW. And it doesn't support Scenes. Maybe you can help me adding entities for scenes in the integration.
> 
> Can I ask you to send me the result of some URLs in your browser?

Would be happy to help. However, I am not really sure what you are asking for.
Can you give me some clearer instructions what exactly you are looking for?

**Comment by peribeir** [comment]
Hi all,

Since my gateway doesn't support scenes, I'll try to guess based on what I read in forums.
Can you try the following?
http://{homepilot_ip}/scenes and/or http://{homepilot_ip}/v4/scenes

**Comment by peribeir** [comment]
Thanks @rhmunich .

Scenes will be added in the next release. I cannot test them on a real device, so I ask you to do it and give feedback.
