### ISSUE TITLE
Support Home Assistant Add-On Store

### ISSUE THREAD

**Issue by deltaphi** [peribeir/homeassistant-rademacher#89]
Home Assistant now offers support for Thord-Party Repositories in its Add-On Store ([Manual](https://www.home-assistant.io/common-tasks/os#installing-third-party-add-ons)). Please support installing homeassistant-rademacher through the Add-On Store. It is a lot less hassle than Using HACS, let alone manually installing and updating the Rademacher Add-On.

**Comment by peribeir** [comment]
Hi @deltaphi 

Third party repos for add-ons have been around for a long time. But this is not an add-on, it is a custom integration.

Add-ons are software packages that run in a different process, and are not normally used for inregration with specific devices (example of an add-on is MariaDB, a database server which can then be used by other components or HA itself to store data).

HACS is the simplest way, as of now and to my knowledge, to integrate new devices which are not supported in HA natively.

So for now, I don't foresee any other way to install this integration.

Thanks for your query.
I'll close the issue.
