### ISSUE TITLE
Upgrade to 1.3.1 from 1.3.0 fails

### ISSUE THREAD

**Issue by hklages** [peribeir/homeassistant-rademacher#9]
Hi thanks for this great integration. It replaces a lot of my "REST API calls" /sensor templates. 

The update to 1.3.0 did work fine (I removed the old integration and folder manually), then used HACS to install 1.3.0

Today I tried to update via HACS from 1.3.0 to 1.3.1 but the update failed an all my covers were unavailable. 
Unfortunately I can not provide you with any log messages. Sorry for that.  I had to restore a full backup because I accidentally deleted important HA files as I tried to get the covers work again. :-(

So this is just a "heads up" message. Would be interesting whether others also had the issues. 

Installation with newest software:  
HomePilot 2 
- 2 x RADEMACHER RolloTron Comfort DuoFern Gurtwickler 1800-UW
- 4 x RADEMACHER RolloTron Standard DuoFern Gurtwickler 1400-UW
- 2 x RADEMACHER Sonnen- / Dämmerungssensor, 0,75 m (not used)

**Comment by peribeir** [comment]
Hi,

I'm sorry to hear that it failed :(

I'll try to reproduce the issue (downgrade then upgrade) to see if it happens to me too.

One question, after the upgrade, did you try to remove the integration and then add again?

**Comment by kauthmbt** [comment]
@peribeir 
Having the same problem too.
According to the logs it seems to be related to the following line added to several files:
`devices: bool = entry[2][CONF_DEVICES]`

```
2022-01-18 10:26:43 ERROR (MainThread) [homeassistant.components.cover] Error while setting up rademacher platform for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/rademacher/cover.py", line 35, in async_setup_entry
    devices: bool = entry[2][CONF_DEVICES]
KeyError: 'devices'
```

Also effecting _button, switch, binary_sensor, sensor_ parts
