### ISSUE TITLE
Safe to Update Homepilot?

### ISSUE THREAD

**Issue by deltaphi** [peribeir/homeassistant-rademacher#90]
In #83 it was discovered that there is a new kind of Gateway that works with the DuoFern devices by Rademacher. I own the older Rademacher HomePilot Gateway, which has been working fine with this Add-On for two years now. My Gateway now offers me an update from SW Version 5.5.10 to 5.7.15. The Changelog boldly states that "Rademacher is now HomePilot". This makes me wonder: Will my gateway become unusable with this Add-On if I do the update, or is it safe to do the update?

**Comment by peribeir** [comment]
Hi @deltaphi 

I own the smaller Start2Smart Gateway which, to my knowledge, shares firmware with Homepilot Gateways (the Rademacher ones).
I have installed all updates and I currently have version 5.7.15
![image](https://github.com/peribeir/homeassistant-rademacher/assets/7266291/776d7b2d-ea84-4cf3-9348-6def844c353f)

Everything is working, and up until now only people with the newer hardware are not able to integrate using this integration.
So, it should be safe to update.
