### ISSUE TITLE
Ventilation position (and ping) entities missing

### ISSUE THREAD

**Issue by K987D** [peribeir/homeassistant-rademacher#92]
I own 6 "Rademacher RolloTron Schwenkwickler Standard DuoFern Minigurt 2550-UW" and I'm happy to see them integrated into Home Assistant with this custom component. Great work! The one thing I noticed though is that the "ventilation position" entity is not available for any of them, it comes in the form of

`number.[your_cover_name]_ventilation_position`

Same goes for the "ping" entity. Any chance to integrate these entities? I can see the ventilation position in the official app but not in Home Assistant 2023.9.3.

@duhow @peribeir @michelde @misa1515

**Comment by peribeir** [comment]
Hi @K987D 

I'm not sure if that's an actual bug. Ventilation Position Entities are created but they are not available unless Ventilation Position Mode is activated (you should also have this switch entity).
If you go to the cover device (from settings -> devices & services), do you see these 2 entities?
![image](https://github.com/peribeir/homeassistant-rademacher/assets/7266291/e2dd0d4b-b456-4281-8234-c721869bea9f)
Then if you activate the Ventilation Position Mode you should be able to see that the Ventilation Position slider should be activated (after a few seconds).
![image](https://github.com/peribeir/homeassistant-rademacher/assets/7266291/f43a56b4-af8f-4696-aee9-0455dc578389)

Regarding the ping entities, they should be created but they are hidden by default.
In the same screen as before you should also see it:
![image](https://github.com/peribeir/homeassistant-rademacher/assets/7266291/f7560c32-91f8-464f-ba40-6932652be9f2)

If you want it to be visible you just need to click the name, then click the config icon on the top right and enable the Visible switch.

Please tell me if this was the problem.

**Comment by peribeir** [comment]
Closing due to no answer
