### ISSUE TITLE
DuoFern-Sonnen-Windsensor 9499 - Support Windsensor 

### ISSUE THREAD

**Issue by Sequine** [peribeir/homeassistant-rademacher#93]
Hello,

is it possible to support the windsensor of the DuoFern-Sonnen-Windsensor 9499?
https://service.rademacher.de/hc/de/sections/360005776939-DuoFern-Sonnen-Windsensor-9499

So far the sensor only show the sun stats in Home Assistant but would be great to also have the wind measurement there.

Thanks

**Comment by peribeir** [comment]
Hi @Sequine 

Can you share the output of the following URL in your browser?
http://{homepilot_ip}/v4/devices?devtype=Sensor

Thanks

**Comment by Sequine** [comment]
Hi @peribeir 
thank you.

Yes sure, here it is:
{"response":"get_meters","meters":[{"description":"Ihre Gerätebeschreibung","deviceGroup":3,"did":30,"automations":[30,50],"readings":{"sun_detected":false,"wind_detected":true},"timestamp":1700423343,"iconSetInverted":0,"iconSet":{"k":"iconset39"},"name":"Windsensor","statusValid":true,"deviceNumber":"32004464","uid":"a903e3_1","visible":true}]}

**Comment by peribeir** [comment]
Thanks.
So, just to confirm.
Your sensor detects if wind is present right.
Does it have wind speed or anything else?

**Comment by peribeir** [comment]
Also, can you send me the output of
http://{homepilot_ip}/devices/30

**Comment by Sequine** [comment]
Here is the output:
{"error_description":"OK","error_code":0,"payload":{"device":{"capabilities":[{"name":"SUN_STOP_EVT_PUSH_TEXT","value":"","read_only":false,"timestamp":-1},{"name":"SUN_STOP_EVT","value":"1","read_only":true,"timestamp":1698833635},{"name":"VERSION_CFG","value":"1.1-2","read_only":false,"timestamp":1700424242},{"name":"PROD_CODE_DEVICE_LOC","value":"32004464","read_only":false,"timestamp":-1},{"name":"REACHABILITY_EVT","value":"true","read_only":true,"timestamp":1700424242},{"name":"NAME_DEVICE_LOC","value":"Windsensor","read_only":false,"timestamp":1698766095},{"name":"PROT_ID_DEVICE_LOC","value":"a903e3_1","read_only":false,"timestamp":-1},{"name":"INTF_ID_DEVICE_LOC","value":"3","read_only":false,"timestamp":-1},{"name":"SUN_START_EVT_PUSH_ENABLED","value":"false","read_only":false,"timestamp":-1},{"name":"WIND_START_EVT","value":"1","read_only":true,"timestamp":1700423943},{"name":"WIND_DETECTION_MEA","value":"false","read_only":false,"timestamp":1700424242},{"name":"ICONSET_LOC","value":"iconset39","read_only":false,"timestamp":1698766082},{"name":"SUN_START_EVT","read_only":true,"timestamp":-1},{"name":"SUN_DETECTION_MEA","value":"false","read_only":false,"timestamp":1698833635},{"name":"DEVICE_TYPE_LOC","value":"3","read_only":false,"timestamp":-1},{"name":"ICONSET_INV_LOC","value":"false","read_only":false,"timestamp":-1},{"name":"SUN_START_EVT_PUSH_TEXT","value":"","read_only":false,"timestamp":-1},{"name":"WIND_STOP_EVT_PUSH_TEXT","value":"","read_only":false,"timestamp":-1},{"name":"PAIRING_CONFIRMED_LOC","value":"true","read_only":false,"timestamp":-1},{"name":"ID_DEVICE_LOC","value":"30","read_only":false,"timestamp":-1},{"name":"PROTOCOL_ID_CFG","value":"a903e3","read_only":false,"timestamp":-1},{"name":"WIND_STOP_EVT","value":"1","read_only":true,"timestamp":1698833635},{"name":"WIND_START_EVT_PUSH_ENABLED","value":"false","read_only":false,"timestamp":-1},{"name":"SUN_STOP_EVT_PUSH_ENABLED","value":"false","read_only":false,"timestamp":-1},{"name":"WIND_START_EVT_PUSH_TEXT","value":"","read_only":false,"timestamp":-1},{"name":"VIS_DEVICE_LOC","value":"true","read_only":false,"timestamp":-1},{"name":"WIND_STOP_EVT_PUSH_ENABLED","value":"false","read_only":false,"timestamp":-1},{"name":"DESCR_DEVICE_LOC","value":"Ihre Gerätebeschreibung","read_only":false,"timestamp":1698765968}],"scenes":[],"automation":[]}}}

**Comment by Sequine** [comment]
> Thanks. So, just to confirm. Your sensor detects if wind is present right. Does it have wind speed or anything else?

The sensor has wind speed but I'm not sure if sends it to the Bridge.
On the Bridge via the Rademacher App the sensor only shows as wind or no wind but on the device itself is a display that can show the wind speed.

**Comment by peribeir** [comment]
Indeed, it doesn't report any wind speed value. I'll be adding the wind detected sensor to the next version then.

**Comment by Sequine** [comment]
Great, thank you ver much
