### ISSUE TITLE
Which Homepilot gateways are supported ? 

### ISSUE THREAD

**Issue by raskas** [peribeir/homeassistant-rademacher#94]
Which versions of the Homepilot gateway are supported ? 

I have read that there is a new gateway premium which doesn't work.
https://www.reddit.com/r/homeassistant/comments/15239o6/homepilot_gateway_premium_with_ha/

Can you verify and explicitly mention in the documentation which hardware version is supported and which isn't ? 

Thank you!

**Comment by peribeir** [comment]
Added to README (Hardware support section).
Currently, only Rademacher brand Gateways are currently supported, not the new Gateway Premium from Homepilot (new brand).
Maybe with some support from the community, I can add support in the future.
